---
title: "CVsNPLSlib_profvis"
author: "Baptiste"
date: '2022-06-24'
runtime: shiny
output: html_document
---

```{r setup, include=TRUE, warning=FALSE, cache=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Profvis with source inside the library

# Method

Open new R session or restrat your current one

```{r method}
install.packages("NAME OF LIBRARY TO PROFILE", type="source", INSTALL_opts="--with-keep.source")

'
profvis::profvis({

  # code to profile  
  # if the code too fast, as Rprof record every sample of time it might record anything 
  
})
'
```
Then a window with the results open. You can save it manually as html file by writing .html at the end.

# sNPLS model with random dataset (100x100x3)

```{r model, eval=FALSE}
install.packages("sNPLS", type="source", INSTALL_opts="--with-keep.source")

library(sNPLS)
library(shiny)
library(profvis)

s <- profvis({
  
  X_npls <- array(rpois(7500, 10), dim=c(50, 50, 3))
  Y_npls <- matrix(2+0.4*X_npls[,5,1]+0.7*X_npls[,10,1]-0.9*X_npls[,15,1]
                   +0.6*X_npls[,20,1]-0.5*X_npls[,25,1]+rnorm(50), ncol=1)

  repcv <- repeat_cv(X_npls, Y_npls, ncomp=1:3, keepJ = 1:3,
                   keepK = 3, parallel = FALSE, times=3)

})

htmlwidgets::saveWidget(s, "CVsNPLS_library_profvis.html")

renderUI(s)
```
